### ISSUE TITLE
End effector orientation

### ISSUE THREAD

**Issue by lxkim814** [yzqin/sapien_vacuum_suction_example#1]
Hi, I would like to ask how to force the end effector's orientation to be aligned with a certain vector, say [1,0,0]?  In your repo, I see the robot facing downward to touch the top surface of the boxes, but are there any ways to touch them from other sides?

**Comment by yzqin** [comment]
Hi @lxkim814 

You can do that by modify the poses in [this line](https://github.com/yzqin/sapien_vacuum_suction_example/blob/ebebe56da187a40848b6d0200689cbc125351277/sapien_vaccum_gripper_example.py#L156C18-L156C18)

```python
scene.create_drive(ee_link, connecting_pose_in_first_link, grasped_box, connecting_pose_in_second_link)
```

By modifying the two pose in this function you can control the relative pose between the two object, e.g. how to weld the end effector and the object.

**Comment by lxkim814** [comment]
I think the issue comes from move_robot() function before that "create_drive" line.

I actually want the robot to approach toward the front surface of a cube instead of its top surface. To do that, I believe I have to modify delta_rot from move_robot() function so that the end effector rotates every step while it is getting closer to the cube. 

However, I am not so sure how to find delta_rot. All I know is that end effector has to be aligned with vector (1,0,0) when it's touching the front surface of a cube.

**Comment by yzqin** [comment]
Hi I think you are looking for a general IK solver to move the robot end effector, which is actually not related to the suction modeling of this repo. You can take a look for [the other repo](https://github.com/yzqin/dexpoint-release) and run the examples. The IK code to do what you want can also be found in [this](https://github.com/yzqin/dexpoint-release/blob/3f181586c6ad09cd808d2ae6d451e61de17a0fa3/dexpoint/env/rl_env/base.py#L442).

Feel free to create an issue in the other repo about the inverse kinematics problem you meet for rotate the robot.

**Comment by lxkim814** [comment]
I understood, will have a look at them. I appreciate your help!!
